version: 2.1

jobs:
  install_dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: v1-output
      - run: npm run build
      - save_cache:
          key: v1-output
          paths:
            - dist
  check_quality:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: v1-output
      - run: npm run lint
      - run: npm test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - check_quality:
          requires:
            - build
