version: 2.1

jobs:
  dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: npm install
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  quality:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run lint
      - run: npm test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - dependencies
      - build:
          requires:
            - dependencies
      - quality:
          requires:
            - build

####################################################################################################

# version: 2.1

# jobs:
#   dependencies:
#     docker:
#       - image: circleci/ruby:2.5.1-node-browsers
#     steps:
#       - checkout
#       - run: npm install
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - node_modules/
#   build:
#     docker:
#       - image: circleci/ruby:2.5.1-node-browsers
#     steps:
#       - checkout
#       - run: npm run build
#       - attach_workspace:
#           at: ~/project
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - dist/
#   quality:
#     docker:
#       - image: circleci/ruby:2.5.1-node-browsers
#     steps:
#       - checkout
#       - run: npm run lint
#       - run: npm test
#       - attach_workspace:
#           at: ~/project
#       - persist_to_workspace:
#           root: ~/project
#           paths:
#             - coverage/

# workflows:
#   version: 2.1
#   build_and_test:
#     jobs:
#       - dependencies
#       - build:
#           requires:
#             - dependencies
#       - quality:
#           requires:
#             - build
