version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: npm install
      - run: npm run build
  quality:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - run: npm run lint
      - run: npm test

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - quality
        requires:
          - build
