version: 2.1

jobs:
  dependencies:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  lint:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm run lint
  build:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: v1-output
      - run: npm run build
      - save_cache:
          key: v1-output
          paths:
            - dist
  documentation:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - run: npm run docs
  test:
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
    steps:
      - checkout
      - restore_cache:
          key: v1-dependency-cache-{{ checksum "package.json" }}
      - restore_cache:
          key: v1-output
      - run: npm run test:codacy

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - build:
          requires:
            - dependencies
      - documentation:
          requires:
            - dependencies
      - test:
          requires:
            - dependencies
            - build
